### ISSUE TITLE
Add a no index on the staging

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/swissgamesgarden#102]
![Screenshot 2022-08-19 at 09 48 56](https://user-images.githubusercontent.com/27284929/185578999-d07dfb5a-7c2d-47ae-be0e-3caa241d90d8.png)

**Comment by WengerK** [comment]
See https://staging.swissgames.garden/robots.txt

**Comment by WengerK** [comment]
@CamilleLetang do we have an account Google Console to remove the already indexed page ? 

https://passwordprotectwp.com/remove-indexed-pages-files-google/#:~:text=Head%20over%20to%20your%20Google,t%20index%20such%20page%20again

**Comment by CamilleLetang** [comment]
@WengerK If we have one, I am not aware of it.
cc. @tonifisler

**Comment by WengerK** [comment]
> @WengerK If we have one, I am not aware of it. cc. @tonifisler

created with @yrochat few minutes ago ! Added to our password manager :)
