### ISSUE TITLE
Problem with Taxinomy "Genres" + "State"

### ISSUE THREAD

**Issue by DavidJavet** [Games-of-Switzerland/swissgamesgarden#126]
I created the "Horror" and "Online Multiplayer" new genres. They appear with a "genres." in front.
Also, there's a strange "M^Multiplayer" genre that doesn't seem linked to any games.

Whatsmore, a similar problem seems to appear in "State". With "Canceled" games appearing as "State.canceled"
<img width="755" alt="Capture d’écran 2023-01-25 à 14 34 47" src="https://user-images.githubusercontent.com/13621847/214578238-280a25f0-385e-4058-913c-1ad98f2be4f2.png">
<img width="755" alt="Capture d’écran 2023-01-25 à 14 34 24" src="https://user-images.githubusercontent.com/13621847/214578257-d953646b-5e59-48ba-b583-ea6f337532a0.png">
<img width="765" alt="Capture d’écran 2023-01-25 à 14 34 39" src="https://user-images.githubusercontent.com/13621847/214578277-8567832b-cf51-4221-9d3b-2dcc18778f47.png">
<img width="875" alt="Capture d’écran 2023-01-25 à 14 34 32" src="https://user-images.githubusercontent.com/13621847/214578289-c9fd27d2-58a5-4ce7-9b80-59249d591357.png">

**Comment by WengerK** [comment]
That's because all those labels are translatable and therfore they must be defined into our translations strings

https://github.com/Games-of-Switzerland/swissgamesgarden/blob/dev/src/locales/en.json

**Comment by WengerK** [comment]
I openned a PR with fixed translations "m^multiplayer" and new missing translations.

https://github.com/Games-of-Switzerland/swissgamesgarden/pull/129

May you review it @DavidJavet ?

**Comment by DavidJavet** [comment]
@WengerK THANKS! Should be good (sorry if I'm missing something)!
