### ISSUE TITLE
Ratio of figures shouldn't be modified

### ISSUE THREAD

**Issue by yrochat** [Games-of-Switzerland/swissgamesgarden#130]
Example: https://swissgames.garden/games/train

**Comment by WengerK** [comment]
There is a frontend issue indeed I'l take a look asap

**Comment by WengerK** [comment]
ping @tonifisler do we have a better solution than removing `w-full` ?

**Comment by WengerK** [comment]
I merged a PR that should fix this @yrochat can you tests on staging ?

https://staging.swissgames.garden/

you may check diff on the same game:
- Prod: [swissgames.garden/games/train](https://swissgames.garden/games/train)
- Staging: [staging.swissgames.garden/games/train](https://staging.swissgames.garden/games/train)

**Comment by yrochat** [comment]
Dear @WengerK,
This looks wonderful. I've also had a look at other pages with vertical images (e.g. mobile games) and it worked great. Thank you so much!
