### ISSUE TITLE
Change "pre-release" state to "prototype"

### ISSUE THREAD

**Issue by yrochat** [Games-of-Switzerland/swissgamesgarden#132]
With David, we would like to replace the "pre-release" state by "prototype". This term would be able to include unfinished student projects, game jam games, and actual prototype.

**Comment by WengerK** [comment]
I see

<img width="1265" alt="Screenshot 2023-04-05 at 16 24 27" src="https://user-images.githubusercontent.com/1841592/230111120-eef405eb-9899-400b-842f-624e7350767b.png">

Can I suggest to add "prototype" instead ? before pre-release for example ?

**Comment by yrochat** [comment]
Yes, it also works. Thanks!

**Comment by WengerK** [comment]
C'est testable sur le staging @yrochat 

Backend: https://staging-api.swissgames.garden
Frontend: https://staging.swissgames.garden

**Comment by yrochat** [comment]
Hello Kevin,

C'est parfait, pour David comme pour moi ! Merci beaucoup pour ton travail.

Amitiés,

Yannick

Le jeu. 6 avr. 2023 à 13:08, Kevin Wenger ***@***.***> a
écrit :
