### ISSUE TITLE
In the case of more than one studio, we need commas or line breaks to separate them

### ISSUE THREAD

**Issue by yrochat** [Games-of-Switzerland/swissgamesgarden#140]
<img width="385" alt="Capture d’écran 2023-06-29 à 11 14 41" src="https://github.com/Games-of-Switzerland/swissgamesgarden/assets/3351331/625c5eb3-59df-47ec-887d-72857c55d963">

Source : https://swissgames.garden/games/buzanglo

**Comment by yrochat** [comment]
This looks great. Thank you!

**Comment by WengerK** [comment]
I close and will trigger a release once I have receive a response on #149 and added the missing translations <3
