### ISSUE TITLE
Taxinomy problems : Prototype (State) & Platforms & Online Multiplayer

### ISSUE THREAD

**Issue by DavidJavet** [Games-of-Switzerland/swissgamesgarden#149]
- [x] In the "State" filter bar, "Prototype" appears as: states.prototype
- [x] Same thing with the new "Platforms" we added in the "Platforms" filter bar: plaforms.acorn_archimedes / plaforms.AppleIIGS / platforms_CDC1604 / plaforms.playdate / 
- [x] Same thing with new "Cantons" in the "Cantons" filter bar : canton.zug
- [x] There a problem with the Online Multiplayer genre tag: https://swissgames.garden/?genres[]=online_multiplayer

**Comment by WengerK** [comment]
Thx for you feedbacks !

Can you give me the final translations for the platforms ?
I hypotheses its, but like a confirmation:

- `plaforms.acorn_archimedes` = Archimdes
- `plaforms.AppleIIGS` = Apple II GS
- `platforms_CDC1604` = CDC 1604
- `plaforms.playdate` = Play Date

I'll take care of the other translations.

I have created a separate issue to track the visual glitch with Online Multiplayer tag

**Comment by DavidJavet** [comment]
> Thx for you feedbacks !
> 
> Can you give me the final translations for the platforms ? I hypotheses its, but like a confirmation:
> 
> * `plaforms.acorn_archimedes` = Archimdes
> * `plaforms.AppleIIGS` = Apple II GS
> * `platforms_CDC1604` = CDC 1604
> * `plaforms.playdate` = Play Date
> 
> I'll take care of the other translations.
> 
> I have created a separate issue to track the visual glitch with Online Multiplayer tag

Great! Thanks for all your help with this!
Correct orthograph for these platforms are:
- Acorn Archimedes
- Apple IIGS
- CDC 1604
- Playdate
