### ISSUE TITLE
Improve Game Teaser with multiple Genres & Platforms with +X mention

### ISSUE THREAD

**Issue by WengerK** [Games-of-Switzerland/swissgamesgarden#150]
**💬 Demand**
There a problem with the Online Multiplayer genre tag: [https://swissgames.garden/?genres[]=online_multiplayer](https://swissgames.garden/?genres%5B%5D=online_multiplayer)

<img width="1840" alt="Screenshot 2024-02-26 at 08 26 23" src="https://github.com/Games-of-Switzerland/swissgamesgarden/assets/1841592/4109b408-5de8-4250-9cd8-8d70fbd5634f">

**🔢 Tasks**

**🎟 Reported on** 
https://github.com/Games-of-Switzerland/swissgamesgarden/issues/149 by @DavidJavet

**Comment by WengerK** [comment]
fixed on staging @DavidJavet (URL to review: https://staging.swissgames.garden)

**Comment by DavidJavet** [comment]
> fixed on staging @DavidJavet (URL to review: https://staging.swissgames.garden).
> 
> Thanks for confirming it works as you expected.
> 
> <img alt="Screenshot 2024-02-26 at 09 27 43" width="1840" src="https://private-user-images.githubusercontent.com/1841592/307715122-b0480144-be1e-48d5-96c3-b5796840fc84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5Mzg0NTQsIm5iZiI6MTcwODkzODE1NCwicGF0aCI6Ii8xODQxNTkyLzMwNzcxNTEyMi1iMDQ4MDE0NC1iZTFlLTQ4ZDUtOTZjMy1iNTc5Njg0MGZjODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMDkwMjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWQ1YTNiYWQzYzVlOTMxODA1MTEzNjA4ZjFmMTY4YzZhOGM5Y2I5MDk4NjE5NzJlOTU4ZWEyZDdkNWVhZjJkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zQB6cInKFxMKwygP3tyjRCPXk6vT9v69b-PaCASAaoE">


I am afraid this is not a good solution as the game image is unseable if we registered too many Platforms and Genres. The Game image should always take priority to the tags in my opinion.

**Comment by WengerK** [comment]
Thanks for your message, therefore it's out of my skills and needs design to fit your needs.
Something with a [+1] or [+x] should be done

Do you want to propose something or do you prefer requesting helps from Pierre Georges ?

**Comment by DavidJavet** [comment]
I guess the best solution would be that after 1 entry (or 2 entries) of either "Genres" or "Platforms" we should see a [...]. Do you think that's feasible (without too much effort), or should we put that in the "nice-to-have" or "to have when budget" list?

**Comment by WengerK** [comment]
I can try something like that (not sure I will be able to do it [my frontend skills are limited] stil I can try)

<img width="286" alt="Screenshot 2024-02-26 at 10 42 53" src="https://github.com/Games-of-Switzerland/swissgamesgarden/assets/1841592/1338b261-3f46-4c1e-9bec-72eea7a0cd6a">

**Comment by DavidJavet** [comment]
You're amazing! Thanks a lot for trying!

**Comment by WengerK** [comment]
Here is the best I can achieve 

Listing with +x elements
<img width="1840" alt="Screenshot 2024-02-28 at 19 09 12" src="https://github.com/Games-of-Switzerland/swissgamesgarden/assets/1841592/00c00a5e-45ae-4372-9566-41a5c38553c5">

Popover
<img width="1840" alt="Screenshot 2024-02-28 at 19 09 14" src="https://github.com/Games-of-Switzerland/swissgamesgarden/assets/1841592/3fe310ef-4a91-42b5-8c7b-f57d8aa3ef02">
<img width="1840" alt="Screenshot 2024-02-28 at 19 09 15" src="https://github.com/Games-of-Switzerland/swissgamesgarden/assets/1841592/da52f0c8-4290-4fdc-bfe5-4b600ab0001d">

**Comment by WengerK** [comment]
testable on staging @DavidJavet

**Comment by DavidJavet** [comment]
> Here is the best I can achieve

- Looks great for me! That seems like a good solution.

> 
> **Listing with +x elements** <img alt="Screenshot 2024-02-28 at 19 14 15" width="1840" src="https://private-user-images.githubusercontent.com/1841592/308667169-e99a5d5d-365d-4b7b-a297-afac5d79fa17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDA5NTcsIm5iZiI6MTcwOTU0MDY1NywicGF0aCI6Ii8xODQxNTkyLzMwODY2NzE2OS1lOTlhNWQ1ZC0zNjVkLTRiN2ItYTI5Ny1hZmFjNWQ3OWZhMTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMDgyNDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDZkY2U2Yzk5OGEzMWI2MjIzMDQ2OWEzNzQzZDlkYjYwYjNhYzA0MGVjMDFiYTU2OGNjYTNlMzMxM2ZlM2ZhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-hYVu_3cIwsTE0wwVHQ79quhPfdf_JUjJGjgxo_KlsE">
> 
> **Popover** <img alt="Screenshot 2024-02-28 at 19 14 17" width="1840" src="https://private-user-images.githubusercontent.com/1841592/308667194-68e10d6e-fe83-438b-b214-351d6af3a152.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDA5NTcsIm5iZiI6MTcwOTU0MDY1NywicGF0aCI6Ii8xODQxNTkyLzMwODY2NzE5NC02OGUxMGQ2ZS1mZTgzLTQzOGItYjIxNC0zNTFkNmFmM2ExNTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMDgyNDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjBhYjcwNTVjYjkyZmM5YzE0YTdjMWUxNWI1OWVkYWM5ZTQxZDQ4MTdlODgwZGM1NzRhMmExMTA1Yjc2NGJjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oQ5ZSiNw3aqrO-YwCI7sAGr7Qh3PyzyH48_M_Nbsv_o">
