### ISSUE TITLE
Add empty state to games list

### ISSUE THREAD

**Issue by tonifisler** [Games-of-Switzerland/swissgamesgarden#28]

**Comment by CamilleLetang** [comment]
@WengerK could you please review, I don't understand what I am supposed to test. thanks

**Comment by WengerK** [comment]
go to https://staging.swissgames.garden/?platforms[]=ios&stores[]=asdf

must display the ghost

<img width="1904" alt="Screenshot 2022-09-09 at 18 07 10" src="https://user-images.githubusercontent.com/1841592/189393873-b52f78ad-a102-414e-8104-ed8ac1e3c8a2.png">


I fixed it 

<img width="1904" alt="Screenshot 2022-09-09 at 18 07 12" src="https://user-images.githubusercontent.com/1841592/189393895-d9017966-3dde-4643-b15e-e0b037cc799b.png">
