### ISSUE TITLE
Missing source design

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/swissgamesgarden#44]
<img width="1181" alt="Capture d’écran 2020-11-07 à 11 15 24" src="https://user-images.githubusercontent.com/27284929/98438547-3e539300-20eb-11eb-9780-ef6e45778fb0.png">

https://projects.invisionapp.com/share/ZRUVZ9XXHQV#/screens/393934326

**Comment by WengerK** [comment]
Toni did something it seems (2 commits referencing this issue) therefore, I think you can review what has been done

**Comment by WengerK** [comment]
source seems visible

https://swissgames.garden/games/asd-tower-defense

<img width="529" alt="Screenshot 2022-09-10 at 17 22 13" src="https://user-images.githubusercontent.com/1841592/189490030-519fac52-d59f-437d-aec6-729f159a9de5.png">
