### ISSUE TITLE
Missing articles list + communiqués de presse design

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/swissgamesgarden#45]
<img width="751" alt="Capture d’écran 2020-11-07 à 11 16 35" src="https://user-images.githubusercontent.com/27284929/98438572-63e09c80-20eb-11eb-8865-54f3830a8657.png">

https://projects.invisionapp.com/share/ZRUVZ9XXHQV#/screens/393934326

**Comment by WengerK** [comment]
Toni did something it seems (2 commits referencing this issue) therefore, I think you can review what has been done

**Comment by WengerK** [comment]
seems working on prod https://swissgames.garden/games/pamehta

<img width="337" alt="Screenshot 2022-09-10 at 17 24 03" src="https://user-images.githubusercontent.com/1841592/189490120-0fe33370-f686-4d85-8e96-e6331d1f523f.png">
