### ISSUE TITLE
Game listing - Filters - filters in general - should display uppercase, space, and punctuation

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/swissgamesgarden#50]
<img width="852" alt="Capture d’écran 2020-11-07 à 11 53 11" src="https://user-images.githubusercontent.com/27284929/98439118-d94e6c00-20ef-11eb-9749-1deb7a66ff9d.png">

https://staging-api-gos.museebolo.ch/admin/structure/taxonomy/manage/location/overview

Kufstein (Austria)
Zürich
St. Gallen

**Comment by WengerK** [comment]
isn't just missing translations from loco ? @tonifisler

**Comment by tonifisler** [comment]
As said in Slack, I would love to get those values from the Drupal, it makes no sense to translate them again in Loco

**Comment by WengerK** [comment]
done in https://github.com/Games-of-Switzerland/api.swissgamesgarden/pull/178
