### ISSUE TITLE
Donate page content

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/swissgamesgarden#68]
https://docs.google.com/document/d/1rVeXZ1hdox6kH6a5mT5yAHqe4EtNCMe8gehg4DQ9xsY/edit?usp=sharing

**Comment by CamilleLetang** [comment]
Missing the CTA
[CTA] Donate for Swiss Video Games
url: https://www.paypal.com/paypalme/museebolo

**Comment by CamilleLetang** [comment]
@tonifisler I don't see any update, the page on the staging isn't up to date, and the page on prod hasn't been updated.
Thanks for your help

**Comment by WengerK** [comment]
working close and move as `done`

https://swissgames.garden/donation

<img width="949" alt="Screenshot 2022-09-09 at 16 53 42" src="https://user-images.githubusercontent.com/1841592/189379383-4fbb5448-feb2-439d-9218-055267a33fd2.png">
