### ISSUE TITLE
Contact page content

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/swissgamesgarden#69]
https://docs.google.com/document/d/1rVeXZ1hdox6kH6a5mT5yAHqe4EtNCMe8gehg4DQ9xsY/edit#heading=h.1zyn8ruo5jjw

**Comment by CamilleLetang** [comment]
Missing the linkt to "https://swissgames.garden/add" on "by suggesting a new game here"

**Comment by WengerK** [comment]
Just to be sure, the "add" is for now a simple `mailto` right ? @CamilleLetang

**Comment by CamilleLetang** [comment]
> Just to be sure, the "add" is for now a simple `mailto` right ? @CamilleLetang
> 
> The btn will then open a new mail with a specific content (which is ?? where ?)

Infos about "add a game" email prepop are here: https://github.com/Games-of-Switzerland/gos-website/issues/89
- but waiting Yannick and Robin feedback -
