### ISSUE TITLE
Listing - remove the "fetched in"

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/swissgamesgarden#83]
https://swissgames.garden/
![Screenshot 2022-03-14 at 14 15 48](https://user-images.githubusercontent.com/27284929/158179504-f034d821-68b5-441a-9ad7-63460a0a1502.png)

**Comment by tonifisler** [comment]
It was intended as a "geeky" thingy :) I choose to keep it!

**Comment by CamilleLetang** [comment]
I think it's not understandable, but np to keep it
