### ISSUE TITLE
Search - auto-complete - icons - Studio and People icons should be in colors

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/swissgamesgarden#85]
https://projects.invisionapp.com/share/ZRUVZ9XXHQV#/screens/393934325
![Screenshot 2022-03-14 at 14 36 09](https://user-images.githubusercontent.com/27284929/158183256-546a0232-daca-4174-8787-1376e80c245a.png)

<img width="1213" alt="Screenshot 2022-03-14 at 14 37 28" src="https://user-images.githubusercontent.com/27284929/158183356-3d6c6e62-91c9-4eb3-9c4f-65e13bc111ad.png">

studio in violet
and people in green

**Comment by WengerK** [comment]
![Uploading Screenshot 2022-09-10 at 17.19.45.png…]()
