### ISSUE TITLE
Game detail - complete a game CTA auto-fill the email

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/swissgamesgarden#88]
https://swissgames.garden/games/last-eichhof
<img width="1785" alt="Screenshot 2022-03-14 at 18 03 19" src="https://user-images.githubusercontent.com/27284929/158223255-c4bc5c28-4d20-4785-9298-cb52e35725a1.png">

On the game pages we should populate the "mailto" with:

Subject : "Game update suggestion - [game name]"
Email body: [empty]

**Comment by WengerK** [comment]
removed as requested

<img width="777" alt="Screenshot 2022-09-09 at 17 37 37" src="https://user-images.githubusercontent.com/1841592/189388333-710fa9e2-af95-4ad9-89d9-66f0aa9fc9d1.png">
