### ISSUE TITLE
Submit a game - submit a game CTA - auto-fill the email

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/swissgamesgarden#89]
https://swissgames.garden/add
On the "add a game" page we should populate the "mailto" with:

Subject: "New game suggestion"
Email body: 

"Dear gamer,
Thank you for your participation!

Below is the information needed to add a new game entry. 
It doesn't matter if you don't have all the data, we will be very happy with what you managed to send us!

**General**
Title: 
Summary: 
Image URL or add an attached file: 

**Releases**
Publisher(s): 
Release 1
Release 1 date:
Release 1 platform:
Release 1 state:
(You can add several release dates)

**Authors**
Members
Person 1
Role person 1
(You can add several team members)

Studio(s)
Studio 1 name: 
(You can add several studios)

**Detailed info about the game**
Number of players
Minimum number of players: 
Maximum number of players: 

Store(s)
Store 1:
Link to the game in the store 1:
(You can add several stores)

Location(s)
Where the game's team was working: 
(You can add several locations)

Language(s)
Game's available language 1: 
(You can add several languages)

Genre(s)
Game's genre 1: 
(You can add several genres)

Sponsor(s)
Game's sponsor 1: 
(You can add several sponsors)

**References**
Game's website: 
Articles about the game: 
Game's sources: 
Game's awards: 
Game's social networks link: 
Other links about the game: 
Game's credit: 

**Other**
Any comment or other information you would like to share:

**Comment by yrochat** [comment]
Based on the discussion on Slack, we should give emphasis to the most relevant fields to fill for the contributors.

Title:
Publisher(s):
Release 1 date:
Release 1 platform:
Game's website:

Is that too few? too much?

**Comment by CamilleLetang** [comment]
Note to me: 
"to be able to keep the source of the information, probably without it being public, and therefore to save at least the contact email but if possible also a name or username"
Linked: https://github.com/Games-of-Switzerland/swissgamesgarden/issues/95

**Comment by WengerK** [comment]
can we close this @CamilleLetang ?
