### ISSUE TITLE
About page content

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/swissgamesgarden#9]
En statique 

https://docs.google.com/document/d/1rVeXZ1hdox6kH6a5mT5yAHqe4EtNCMe8gehg4DQ9xsY/edit?usp=sharing

**Comment by CamilleLetang** [comment]
https://github.com/Games-of-Switzerland/gos-website/blob/18e8baa82dfba0262947ba1fcc6ddc474a2708ed/src/locales/en.json

**Comment by CamilleLetang** [comment]
@tonifisler I don't see any update, the page on the staging isn't up to date, and the page on prod hasn't been updated.
Thanks for your help

**Comment by WengerK** [comment]
fixed footernot & content of the page now

**Comment by WengerK** [comment]
postponned adding Robin François if we shoudl still add it, please recreate another issue (as not sure Robin still works at bolo)

**Comment by WengerK** [comment]
you can now add btn on link into Drupal

<img width="1904" alt="Screenshot 2022-09-10 at 16 26 49" src="https://user-images.githubusercontent.com/1841592/189487925-3f61f29c-66f7-4668-be83-952182754a7c.png">

They will show as

<img width="792" alt="Screenshot 2022-09-10 at 16 31 11" src="https://user-images.githubusercontent.com/1841592/189487976-40881fbf-1e41-49cf-bda1-dbad180533b9.png">

**Comment by CamilleLetang** [comment]
Missing Robin's infos (check the bullet above).
c.c. @WengerK @tonifisler

**Comment by WengerK** [comment]
<img width="1904" alt="Screenshot 2022-09-21 at 16 01 26" src="https://user-images.githubusercontent.com/1841592/191525036-0630edfd-d3fe-4a20-9b2a-1dba714b53bc.png">

here it is - new section "consultants" with Robin inside right ?

**Comment by CamilleLetang** [comment]
@WengerK pefect, you can copy your work on prod. Thanks
