### ISSUE TITLE
Insert line breaks or separators between names

### ISSUE THREAD

**Issue by yrochat** [Games-of-Switzerland/swissgamesgarden#98]
<img width="468" alt="Capture d’écran 2022-05-12 à 19 57 24" src="https://user-images.githubusercontent.com/3351331/168138935-f4c5f1af-9d97-4fbe-9411-ed1ab73c01cb.png">

**Comment by WengerK** [comment]
Please add link for debugging :) 

Here -> https://swissgames.garden/games/good-bad-beauty

**Comment by WengerK** [comment]
What do you prefer @yrochat 

# Row

<img width="650" alt="Screenshot 2022-09-09 at 16 26 03" src="https://user-images.githubusercontent.com/1841592/189373161-4fcf870a-7118-41c5-9623-c192adea3a13.png">

`flex flex-wrap justify-between`

# Column

<img width="628" alt="Screenshot 2022-09-09 at 16 25 56" src="https://user-images.githubusercontent.com/1841592/189373192-94b1e88a-b1a4-449b-a1ed-eb80ea42a8d7.png">

`flex flex-col`

**Comment by yrochat** [comment]
I prefer column (could it be a problem if we have a very long list ? I
don't think so…). Thank you!

Le ven. 9 sept. 2022 à 16:27, Kevin Wenger ***@***.***> a
écrit :

**Comment by WengerK** [comment]
That shouls be fine with column
