### ISSUE TITLE
About incomplete release date

### ISSUE THREAD

**Issue by yrochat** [Games-of-Switzerland/swissgamesgarden#99]
How to deal with unknown day or unknown day/month?

<img width="302" alt="Capture d’écran 2022-05-19 à 10 29 18" src="https://user-images.githubusercontent.com/3351331/169251038-22f8537c-7a66-49e2-b634-9aef233887eb.png">

**Comment by WengerK** [comment]
put 01.01 :) we only use the year if'im correct but Drupal cant deal with date whitout d.m informations
